# Generated by Django 5.2 on 2025-04-30 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="task_board_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
